version: '3.9'

services:
  db:
    image: trackmy-db
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_admin_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_admin_password
      POSTGRES_DB: trackmy
    ports:
      - 5432:5432

    secrets:
      - db_admin_password
      - db_admin_user
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
  db_admin_password:
    file: ../secrets/db_admin_password.txt
  db_admin_user:
    file: ../secrets/db_admin_user.txt