version: '3.9'

services:
  db:
    image: trackmy-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: trackmy
    ports:
      - 5432:5432

    secrets:
      - db_password
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
  db_password:
    file: ../secrets/db_password.txt